server:
  port: 8084
  servlet:
    context-path: /
  tomcat:
    uri-encoding: utf-8

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 10MB
      max-request-size: 100MB
  #数据库连接配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/db_pethospital?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false

#客户头像图片存储地址
customerImageFilePath: D://Javaproject/PetHospital-master/src/main/webapp/static/images/customerImage/
#医院人员头像图片存储地址
userImageFilePath: D://Javaproject/PetHospital-master/src/main/webapp/static/images/userImage/
#商品图片存储地址
goodsImageFilePath: D://Javaproject/PetHospital-master/src/main/webapp/static/images/goodsImage/
#宠物图片存储地址
petImageFilePath: D://Javaproject/PetHospital-master/src/main/webapp/static/images/petImage/
#宠物病情图片存储地址
inquiryImageFilePath: D://Javaproject/PetHospital-master/src/main/webapp/static/images/inquiryImage/

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.pingan.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true